### ISSUE TITLE
I added a ground model, but the characters will penetrate the wall

### ISSUE THREAD

**Issue by pxim** [toodom02/AroundTheWorld#1]
Excuse me, can you help me ?
I added a ground model, but the characters will penetrate the wall.

the code
![image](https://user-images.githubusercontent.com/5111701/232654215-533adbdf-6e3c-410d-89c2-f357d2f6b139.png)

the effect
![image](https://user-images.githubusercontent.com/5111701/232654463-8a3581a9-f847-4018-8ac8-35d6e1579a55.png)

added model - collision-world.glb
[collision-world.zip](https://github.com/toodom02/AroundTheWorld/files/11257315/collision-world.zip)

---------------------
![image](https://user-images.githubusercontent.com/5111701/232658482-66df57da-40fb-43c7-ad7c-c278a2293f4a.png)
Please, in addition to the model adding code, what other code do I need to add.

**Comment by toodom02** [comment]
It looks like you're trying defining the shape of the cannon object as a Convex Hull with three-to-cannon.
`const cannonConvert = threeToCannon(gltf.scene, {type: ShapeType.HULL});`

The scene is not a convex shape, though, so in this instance I think the best option would be to define the physics 'world' by manually creating the shapes of each element.
